### ISSUE TITLE
[Pixel Mix] Add spawn kits

### ISSUE THREAD

**Issue by fixitqixit** [OvercastCommunity/Issues#37]
# Map name
Pixel Mix by DoomRobotBoy

## Describe the bug
Sometimes the regions that apply kits to players do not work, essentially breaking the map as players spawn without these kits.

## Expected behavior
Players should be given the spawn kit upon entering their respective spawn regions.

### Proposed fix
A simple fix will be to add spawn kits.

**Comment by Brottweiler** [comment]
I think the AC sometimes teleports players down bypassing the region which gives you a kit. This is obviously not a map bug, _but_ maps that give spawnkits via regions instead of at spawn is annoying anyway so this is a good fix.

Another map that does this is Turf Wars. Adding a spawnkit on Turf Wars instead of it being region based would be nice because you can customize your spawnkit while falling down.

**Comment by jexeI** [comment]
Turf wars now has a kit too
